[package]
name = "digirain"
description = "Digital rain terminal animation."
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
doodle.path = "../doodle"
clap = { workspace = true, features = ["derive"] }
crossterm.workspace = true
rand.workspace = true

[build-dependencies]
winresource.workspace = true
