[package]
name = "doodles"
description = "Miscellaneous Rusty Doodles"
authors = ["Jonathon Burnham Cobb"]
version = "0.1.0"
edition = "2024"

[[bin]]
name = "doodle"
path = "src/doodle/main.rs"

[[bin]]
name = "conway"
path = "src/conway/main.rs"

[[bin]]
name = "digirain"
path = "src/digirain/main.rs"

[[bin]]
name = "maze"
path = "src/maze/main.rs"

[[bin]]
name = "ripples"
path = "src/ripples/main.rs"

[[bin]]
name = "sorty"
path = "src/sorty/main.rs"

[profile.release]
opt-level = 3
lto = true

[dependencies]
bitflags = "2.10.0"
bitvec = "1.0.1"
clap = { version = "4.5.51", features = ["derive"] }
crossterm = "0.29.0"
ctrlc = "3.5.1"
rand = "0.9.2"

[build-dependencies]
winresource = "0.1.31"
