[package]
name = "sorty"
description = "Visualizes different sorting algorithms."
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
bitvec.workspace = true
doodle.path = "../doodle"
clap = { workspace = true, features = ["derive"] }
crossterm.workspace = true
rand.workspace = true

[build-dependencies]
winresource.workspace = true
